const navItems=[['Home','index.html'],['About','about.html'],['Services','services.html'],['Projects','projects.html'],['Progress','progress.html'],['Gallery','gallery.html'],['Blog','blog.html'],['Learning','learning.html'],['Consulting','consulting.html'],['Contact','contact.html']];
const page=location.pathname.split('/').pop()||'index.html';
document.querySelectorAll('[data-header]').forEach(el=>el.innerHTML=`<div class="announcement">Professional civil engineering, construction & consulting services across Nepal</div><header class="site-header"><div class="container nav"><a class="brand" href="index.html"><span class="brand-mark"><span>H</span></span>HIRAKALA BUILD<br>& CONSULT</a><nav class="nav-links" id="navLinks">${navItems.map(([n,u])=>`<a class="${page===u?'active':''}" href="${u}">${n}</a>`).join('')}<a class="btn" href="quote.html">Request a Quote</a></nav><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button></div></header>`);
document.querySelectorAll('.menu-toggle').forEach(b=>b.onclick=()=>{let n=document.querySelector('.nav-links');n.classList.toggle('open');b.setAttribute('aria-expanded',n.classList.contains('open'))});
document.querySelectorAll('.menu-toggle').forEach(b=>b.textContent='Menu');
document.querySelectorAll('[data-footer]').forEach(el=>el.innerHTML=`<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="index.html" style="color:white"><span class="brand-mark"><span>H</span></span>HIRAKALA BUILD<br>& CONSULT</a><p>Professional Civil Engineering & Construction Consultancy across Nepal.</p><div class="socials"><a href="https://www.facebook.com/Hirakalabuildandconsult" target="_blank" rel="noopener noreferrer" aria-label="Visit Hirakala Build & Consult on Facebook">f</a><a href="https://www.instagram.com/hirakalabuildandconsult/" target="_blank" rel="noopener noreferrer" aria-label="Visit Hirakala Build & Consult on Instagram">◎</a><a href="https://www.linkedin.com/company/131904161/" target="_blank" rel="noopener noreferrer" aria-label="Visit Hirakala Build & Consult on LinkedIn">in</a><a href="https://www.youtube.com/@HirakalaBuildandConsult" target="_blank" rel="noopener noreferrer" aria-label="Visit Hirakala Build & Consult on YouTube">▶</a></div></div><div><h3>Quick Links</h3><ul><li><a href="about.html">About</a></li><li><a href="services.html">Services</a></li><li><a href="projects.html">Projects</a></li><li><a href="blog.html">Blog</a></li><li><a href="learning.html">Learning</a></li></ul></div><div><h3>Services</h3><ul><li>Building Design</li><li>Structural Design</li><li>Surveying</li><li>BOQ & Estimation</li><li>Construction</li><li>BIM & Digital Engineering</li></ul></div><div><h3>Contact</h3><ul><li>+977-9851206290</li><li>hirakalabuildandconult@gmail.com</li><li>All Over Nepal</li><li><a href="https://rupendrakhattri.com.np/" target="_blank" rel="noopener noreferrer">Rupendra Khattri Personal Website ↗</a></li><li><a href="contact.html">Talk to an Engineer →</a></li></ul></div></div><div class="container copyright">© 2026 Hirakala Build & Consult Pvt. Ltd. All Rights Reserved.</div></footer><a class="whatsapp" href="https://wa.me/9779851206290" target="_blank" aria-label="Chat on WhatsApp">◔</a>`);
document.querySelectorAll('form:not([data-enquiry-form])').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();let n=f.querySelector('[data-form-note]');if(n){n.textContent='Thank you. Your request has been recorded for follow-up by our engineering team.';n.hidden=false}f.reset()}));
document.querySelectorAll('a[href="https://www.tiktok.com/"]').forEach(a=>{a.href='https://www.tiktok.com/@hirakala.buildandconsult';a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label','Visit Hirakala Build & Consult on TikTok')});
document.querySelectorAll('[data-filter]').forEach(group=>group.addEventListener('click',e=>{if(!e.target.matches('.filter'))return;group.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');let key=e.target.dataset.value;document.querySelectorAll('[data-category]').forEach(c=>c.hidden=key!=='All'&&!c.dataset.category.split(' ').includes(key))}));
